Add Api 16 and 24 testing to Circle CI

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -95,7 +95,70 @@ jobs:
             set -e
             python -m pytest -v tests/adbe_tests.py  --durations=0
 
-  test-python3:
+  test-python3-android-api-16:
+    docker:
+      # Specify service dependencies here if necessary
+      # CircleCI maintains a library of pre-built images
+      # documented at https://circleci.com/docs/2.0/circleci-images/
+      - image: circleci/android:api-28-alpha
+        environment:
+          JVM_OPTS: -Xmx3200m
+
+    working_directory: ~/adb-enhanced-code-checkout-directory
+
+    steps:
+      - checkout
+
+      # Download and cache dependencies
+      - restore_cache:
+          keys:
+          - v1-dependencies-{{ checksum "requirements.txt" }}-28
+          # fallback to using the latest cache if no exact match is found
+          - v1-dependencies-
+
+      - run:
+          name: Install Python dependencies
+          command: |
+            sudo apt-get install python3 python3-pip python3-venv
+            # Setup python3
+            python3 -m venv venv
+            . venv/bin/activate
+            pip3 install -r requirements.txt
+
+      - run:
+          name: Setup Android emulator
+          command: |
+            # echo "Listing of /opt/android/sdk"
+            # ls /opt/android/sdk
+            set -e
+            sdkmanager "system-images;android-16;default;armeabi-v7a"
+            echo "no" | avdmanager create avd -n test -k "system-images;android-16;default;armeabi-v7a"
+
+      - save_cache:
+          paths:
+            - ./venv
+          key: v1-dependencies-{{ checksum "requirements.txt" }}-28
+
+      - run:
+          name: Launch emulator
+          command: export LD_LIBRARY_PATH=${ANDROID_HOME}/emulator/lib64:${ANDROID_HOME}/emulator/lib64/qt/lib && emulator64-arm -avd test -noaudio -no-boot-anim -no-window -accel on
+          background: true
+
+      - run:
+          name: Wait for emulator
+          command: circle-android wait-for-boot
+
+      - run:
+          name: Python 3 tests
+          command: |
+            # Any failure is a failure
+            set -e
+            python3 -m venv venv
+            . venv/bin/activate
+            # echo "Doing an ls"
+            python3 -m pytest -v tests/adbe_tests.py  --durations=0
+
+  test-python3-android-api-22:
     docker:
       # Specify service dependencies here if necessary
       # CircleCI maintains a library of pre-built images
@@ -131,7 +194,9 @@ jobs:
             # echo "Listing of /opt/android/sdk"
             # ls /opt/android/sdk
             # I tried API 25 but it is too slow and times out on Circle CI
-            sdkmanager "system-images;android-22;default;armeabi-v7a" && echo "no" | avdmanager create avd -n test -k "system-images;android-22;default;armeabi-v7a"
+            set -e
+            sdkmanager "system-images;android-22;default;armeabi-v7a"
+            echo "no" | avdmanager create avd -n test -k "system-images;android-22;default;armeabi-v7a"
 
       - save_cache:
           paths:
@@ -157,6 +222,71 @@ jobs:
             # echo "Doing an ls"
             python3 -m pytest -v tests/adbe_tests.py  --durations=0
 
+  test-python3-android-api-24:
+    docker:
+      # Specify service dependencies here if necessary
+      # CircleCI maintains a library of pre-built images
+      # documented at https://circleci.com/docs/2.0/circleci-images/
+      - image: circleci/android:api-28-alpha
+        environment:
+          JVM_OPTS: -Xmx3200m
+
+    working_directory: ~/adb-enhanced-code-checkout-directory
+
+    steps:
+      - checkout
+
+      # Download and cache dependencies
+      - restore_cache:
+          keys:
+          - v1-dependencies-{{ checksum "requirements.txt" }}-28
+          # fallback to using the latest cache if no exact match is found
+          - v1-dependencies-
+
+      - run:
+          name: Install Python dependencies
+          command: |
+            sudo apt-get install python3 python3-pip python3-venv
+            # Setup python3
+            python3 -m venv venv
+            . venv/bin/activate
+            pip3 install -r requirements.txt
+
+      - run:
+          name: Setup Android emulator
+          command: |
+            # echo "Listing of /opt/android/sdk"
+            # ls /opt/android/sdk
+            # I tried API 25 but it is too slow and times out on Circle CI
+            set -e
+            sdkmanager "system-images;android-24;default;armeabi-v7a"
+            echo "no" | avdmanager create avd -n test -k "system-images;android-24;default;armeabi-v7a"
+
+      - save_cache:
+          paths:
+            - ./venv
+          key: v1-dependencies-{{ checksum "requirements.txt" }}-28
+
+      - run:
+          name: Launch emulator
+          command: export LD_LIBRARY_PATH=${ANDROID_HOME}/emulator/lib64:${ANDROID_HOME}/emulator/lib64/qt/lib && emulator64-arm -avd test -noaudio -no-boot-anim -no-window -accel on
+          background: true
+
+      - run:
+          name: Wait for emulator
+          command: circle-android wait-for-boot
+
+      - run:
+          name: Test doze
+          command: |
+            # Any failure is a failure
+            set -e
+            python3 -m venv venv
+            . venv/bin/activate
+            # echo "Doing an ls"
+            # test_permissions hangs on Circle CI
+            python3 -m pytest -v tests/adbe_tests.py  --durations=0 -k 'test_doze'
+
 # https://discuss.circleci.com/t/how-to-test-multiple-versions-by-triggering-jobs-with-a-shell-function/11305
 workflows:
   version: 2
@@ -165,4 +295,8 @@ workflows:
       - setup-python2
       - setup-python3
       - test-python2
-      - test-python3
+      - test-python3-android-api-16
+      - test-python3-android-api-22
+      - test-python3-android-api-24
+      # Note: I tried API 25 as well but it is too slow to boot - https://circleci.com/gh/ashishb/adb-enhanced/251
+      # API 26 onwards, only X86 images are available and emulator-x86 simply does not work on Circle CI.
